# Generated by Django 4.1.2 on 2022-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_kategori_alter_movie_aciklama_movie_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='videolar/'),
        ),
    ]
